### ISSUE TITLE
How to get the right libReflexxesTypeII.so

### ISSUE THREAD

**Issue by saprrow** [pantor/frankx#15]
Hi,
I downloaded ReflexxesTypeII.zip and compiled linux64 .so file from it.
When I used g++7.5, the compiling failed. So I used g++4.8 to compile it and succeeded.
But when I import frankx, it showed libReflexxesTypeII.so: invalid ELF header.
So how to get the right libReflexxesTypeII.so?

My os is ubuntu18.04

Thanks for you help!

**Comment by pantor** [comment]
We recommend to use a trajectory generator with constrained jerk, as the Franka is quite sensitive to acceleration discontinuities. Reflexxes Type II does have unconstrained jerk, so we advise to use Type IV. You can also use the integrated trajectory generator, it is however currently quite slow and not time-optimal (yet).

Back to your question. The error message is due to the compiler version mismatch. [This fork](https://github.com/pantor/RMLTypeII) should have the compiler error with up-to-date gcc fixed.
